name: JapneseChat
version: @version@
api-version: "1.13"
main: me.syari.jp_chat.Main
author: sya_ri
website: https://github.com/sya-ri/JapaneseChat
description: "Japanese Chat Converter For Bukkit, Spigot, Paper etc..."